### ISSUE TITLE
WHAT THE FUCK HAPPENED

### ISSUE THREAD

**Issue by fnfporterhi** [LEVIXDDLMAO/Frostbite-FPE#2]
why is it that someone locked the issue on sanics page

**Comment by LEVIXDDLMAO** [comment]
I dont know

**Comment by MemeHoovy** [comment]
@LEVIXDDLMAO you want me to dm Sanco?

**Comment by LEVIXDDLMAO** [comment]
its up to you

**Comment by MemeHoovy** [comment]
well okay, if you want me to, I will

**Comment by LEVIXDDLMAO** [comment]
go ahead

**Comment by MemeHoovy** [comment]
I talked to him, and he said he locked the conversation because it was spamming his email, and he's too lazy to turn it off

**Comment by MemeHoovy** [comment]
![Uploading Screenshot (6073).png…]()

**Comment by MemeHoovy** [comment]
![Screenshot (6073)](https://user-images.githubusercontent.com/97995998/205465359-54789df2-6cff-4429-8587-7095e54259c6.png)

**Comment by LEVIXDDLMAO** [comment]
lol

**Comment by MemeHoovy** [comment]
yeah so sanco wasn't mad

**Comment by LEVIXDDLMAO** [comment]
oh

**Comment by fnfporterhi** [comment]
good god how many tabs do you have open

**Comment by LEVIXDDLMAO** [comment]
he said dont mind them

**Comment by fnfporterhi** [comment]
it was a lot bro

:)


“And there’s a million things I haven’t done…. but just you wait…..” Alexander Hamilton

**Comment by LEVIXDDLMAO** [comment]
:/

**Comment by fnfporterhi** [comment]
good god it left my signature

**Comment by MemeHoovy** [comment]
> good god how many tabs do you have open

a lot

**Comment by fnfporterhi** [comment]
![227AE677-B155-43C4-B626-66499A2C9F47](https://user-images.githubusercontent.com/99343223/205465698-1575643d-19c5-4af4-95ca-c17deb692dcb.jpeg)

nah he’s fine

**Comment by fnfporterhi** [comment]
> > good god how many tabs do you have open
> 
> a lot

that would crash my school chromebook no cap lmao

**Comment by LEVIXDDLMAO** [comment]
omg this isn't gonna get about spammed

**Comment by fnfporterhi** [comment]
nah

**Comment by fnfporterhi** [comment]
ill leave y’all alone don’t worry ☺️

**Comment by LEVIXDDLMAO** [comment]
no its nott that, i just dont want this port to be spamed

**Comment by fnfporterhi** [comment]
ok

**Comment by fnfporterhi** [comment]
what port would you like

**Comment by LEVIXDDLMAO** [comment]
I can open a issue on something else

**Comment by fnfporterhi** [comment]
mine?

**Comment by LEVIXDDLMAO** [comment]
open it on infinity engine let me make a new tab

**Comment by LEVIXDDLMAO** [comment]
dont do it rn

**Comment by MemeHoovy** [comment]
lol

**Comment by MemeHoovy** [comment]
I have over 2000 emails

**Comment by LEVIXDDLMAO** [comment]
here https://github.com/LEVIXDDLMAO/FNF-Infinity-Engine/discussions

**Comment by fnfporterhi** [comment]
hehe imagine i forgot to close this lmao
